language: java

before_install:
  # Gradle
- wget http://services.gradle.org/distributions/gradle-1.8-bin.zip
- unzip gradle-1.8-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.8
- export PATH=$GRADLE_HOME/bin:$PATH

jdk:
  - oraclejdk7
  - openjdk6
  
  
